@echo off

set DOWNLOADS_DIR=%USERPROFILE%\Downloads

set LLVM_BIN_DIR=%DOWNLOADS_DIR%\LLVM-21.1.2-win64\bin
set CLANG_FORMAT_EXE=%LLVM_BIN_DIR%\clang-format.exe

"%USERPROFILE%\Downloads\comment-cleaner\clang-format.exe" --style="{ BasedOnStyle: LLVM,  AlignAfterOpenBracket: Align, AlignArrayOfStructures: None, AlignConsecutiveAssignments: { Enabled: false, AcrossEmptyLines: false, AcrossComments: false, AlignCompound: false, AlignFunctionDeclarations: false, AlignFunctionPointers: false, PadOperators: true }, AlignConsecutiveBitFields: { Enabled: false, AcrossEmptyLines: false, AcrossComments: false, AlignCompound: false, AlignFunctionDeclarations: false, AlignFunctionPointers: false, PadOperators: false }, AlignConsecutiveDeclarations: { Enabled: false, AcrossEmptyLines: false, AcrossComments: false, AlignCompound: false, AlignFunctionDeclarations: true, AlignFunctionPointers: false, PadOperators: false }, AlignConsecutiveMacros: { Enabled: true, AcrossEmptyLines: true, AcrossComments: true, AlignCompound: false, AlignFunctionDeclarations: false, AlignFunctionPointers: false, PadOperators: false }, AlignConsecutiveShortCaseStatements: { Enabled: false, AcrossEmptyLines: false, AcrossComments: false, AlignCaseArrows: false, AlignCaseColons: false }, AlignConsecutiveTableGenBreakingDAGArgColons: { Enabled: false, AcrossEmptyLines: false, AcrossComments: false, AlignCompound: false, AlignFunctionDeclarations: false, AlignFunctionPointers: false, PadOperators: false }, AlignConsecutiveTableGenCondOperatorColons: { Enabled: false, AcrossEmptyLines: false, AcrossComments: false, AlignCompound: false, AlignFunctionDeclarations: false, AlignFunctionPointers: false, PadOperators: false }, AlignConsecutiveTableGenDefinitionColons: { Enabled: false, AcrossEmptyLines: false, AcrossComments: false, AlignCompound: false, AlignFunctionDeclarations: false, AlignFunctionPointers: false, PadOperators: false }, AlignEscapedNewlines: Right, AlignOperands: Align, AlignTrailingComments: { Kind: Always, OverEmptyLines: 0 }, AllowAllArgumentsOnNextLine: true, AllowAllParametersOfDeclarationOnNextLine: true, AllowBreakBeforeNoexceptSpecifier: Never, AllowShortBlocksOnASingleLine: Never, AllowShortCaseExpressionOnASingleLine: true, AllowShortCaseLabelsOnASingleLine: false, AllowShortCompoundRequirementOnASingleLine: true, AllowShortEnumsOnASingleLine: true, AllowShortFunctionsOnASingleLine: All, AllowShortIfStatementsOnASingleLine: Never, AllowShortLambdasOnASingleLine: All, AllowShortLoopsOnASingleLine: false, AllowShortNamespacesOnASingleLine: false, AlwaysBreakAfterDefinitionReturnType: None, AlwaysBreakBeforeMultilineStrings: false, UseTab: Never, IndentWidth: 4, TabWidth: 4, BreakBeforeBraces: Allman, IndentCaseLabels: false, ColumnLimit: 0, AccessModifierOffset: -4, NamespaceIndentation: All, FixNamespaceComments: false, IndentPPDirectives: BeforeHash }" -i "%*"
pause

